spring:
  application:
    name: smkt-cookbook

server:
  port: 4080

  
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    
logging:
  level:
    '[com.antonioalejandro.smkt.cookbook]': DEBUG
    
    
mongodb:
  connection: mongodb://root:secret@localhost:27017/
  database:
    name: smkt
    collection: recipes

id_files_instance: smkt-files
id_oauth_instance: smkt-oauth

oauthBasicAuth: c21hcnRraXRjaGVuYXBwOnNlY3JldA==
